import type { LucideIcon } from 'lucide-react';
import {
  Smartphone,
  Users,
  PenTool,
  Rocket,
  BarChart3,
  Monitor,
  PencilRuler,
  RefreshCw,
  TrendingUp,
  Bot,
  Handshake,
  UserPlus,
  ShoppingCart,
  Brain,
  LineChart,
  Database,
  Cpu,
  Atom,
  Hexagon,
  Server,
  Code2,
  Terminal,
  Building2,
  Globe,
  Boxes,
  Store,
  FileText,
  Tablet,
  Layers,
  User,
  Briefcase,
  Mail,
  Sparkles,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  users: Users,
  'pen-tool': PenTool,
  rocket: Rocket,
  'bar-chart-3': BarChart3,
  'app-window': Monitor,
  'monitor-search': Monitor,
  'pencil-ruler': PencilRuler,
  'refresh-cw': RefreshCw,
  'trending-up': TrendingUp,
  bot: Bot,
  handshake: Handshake,
  contact: UserPlus,
  'shopping-cart': ShoppingCart,
  brain: Brain,
  'line-chart': LineChart,
  database: Database,
  cpu: Cpu,
  atom: Atom,
  hexagon: Hexagon,
  server: Server,
  'code-2': Code2,
  coffee: Terminal,
  terminal: Terminal,
  'building-2': Building2,
  globe: Globe,
  boxes: Boxes,
  store: Store,
  newspaper: FileText,
  'tablet-smartphone': Tablet,
  layers: Layers,
  'user-round': User,
  briefcase: Briefcase,
  mail: Mail,
  sparkles: Sparkles,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = icons[name] ?? Sparkles;
  return <Icon className={className} strokeWidth={1.75} />;
}
